### ISSUE TITLE
build breaks for camus-kafka-coders

### ISSUE THREAD

**Issue by pehrs** [confluentinc/camus#12]
When building camus-kafka-coders it breaks with a missing dependencies to:
io.confluent:kafka-avro-serializer:jar:1.0
and
io.confluent:kafka-schema-registry-client:1.0

Where can I find this code?
-M

**Comment by pehrs** [comment]
There is also a dependency issue with:
org.apache.kafka:kafka_2.10:jar:0.8.2.0-cp
Where do we find this -cp version of Kafka?
-M

**Comment by ewencp** [comment]
Thanks for catching this @pehrs. Fixed in ee1916140b. I noticed this issue and fixed it on our development branch. We just omitted the new packages.confluent.io repository when generating the final version, which you generally wouldn't notice is missing if you're building the whole stack since all the other packages would already be in your local repository.

Right now that patch is on the 1.x branch, so you'll want to check out that branch. However, it's all still tagged as 1.0 so you won't be getting snapshot builds.

**Comment by pehrs** [comment]
@ewencp but where is the source code for these components and where is the fork for the (I assume patched) kafka (0.8.2.0-cp)?

**Comment by ewencp** [comment]
@pehrs Ah, sorry, didn't realize you were looking for the source as well. The kafka-avro-serializer and kafka-schema-registry-client modules are both included in our [schema-registry repository](https://github.com/confluentinc/schema-registry). (We keep these all together since the serializers are one of the few direct users of the kafka-schema-registry-client library and we can share a bit of code between the client and schema registry server).

The 0.8.2.0-cp release doesn't contain anything proprietary, so we haven't even started maintaining a separate repository. We tag it with the extra -cp for two reasons. First, we don't want to conflict with the version numbers for the Apache releases that are pushed to Central, but still be able to use the same version numbers when our releases are closely aligned. Second, we will sometimes release slightly different versions. In this case, our 0.8.2.0-cp is built from 5f3eb1cafaece, which has a few patches that were checked in that will make it into Apache's 0.8.2.1. Let me look into providing a copy of the repository -- we might as well have clearly tagged releases so you can easily find out exactly what's in the release.

**Comment by pehrs** [comment]
@ewencp Thanks for clearing this up :-)
